### ISSUE TITLE
Error: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by shamindras** [ropenscilabs/allcontributors#20]
Thanks for creating this useful package!

I tried applying it locally to an R package git/github repo but keep gettting the following error with `allcontributors::add_contributors()`:

``` R
> allcontributors::add_contributors()
٭  Extracting code contributorsError: $ operator is invalid for atomic vectors
```

However `allcontributors::get_contributors()` works as intended, i.e., returns a dataframe with the expected package contributors.

I tried installing the dev version of `allcontributors` using `pak::pkg_install("mpadge/allcontributors")`. I also restarted my `R` session. Could you please advise how to rectify the issue?

<details>
  <summary>sessionInfo()</summary>

```R
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] allcontributors_0.0.2.009

loaded via a namespace (and not attached):
 [1] ps_1.6.0          pak_0.1.2.9001    digest_0.6.27     R6_2.5.0          jsonlite_1.7.2    git2r_0.28.0     
 [7] magrittr_2.0.1    evaluate_0.14     httr_1.4.2        rlang_0.4.11      cli_3.0.0         curl_4.3.2       
[13] rstudioapi_0.13   callr_3.7.0       rmarkdown_2.9     tools_4.1.1       glue_1.4.2        processx_3.5.2   
[19] yaml_2.2.1        xfun_0.24         compiler_4.1.1    htmltools_0.5.1.1 knitr_1.33       
```

</details>

**Comment by mpadge** [comment]
Thanks @shamindras. To help you out, i need to know the environment from which you're calling the function. From the very helpful GitHub info, I guessed it was what you'd been working on most recently, so tried it in a clone of [`maars`](https://github.com/shamindras/maars), for which it worked perfectly for me, with current `allcontributors` version `0.0.2.6`.

That means I need more info about the issue. If it's related to another package, just let me know which. If it is indeed `maars`, could you please create a *full* [`reprex`](https://github.com/tidyverse/reprex) starting with [`gert::git_clone()`](https://docs.ropensci.org/gert/reference/git_fetch.html) and running `add_contributors()` on the freshly cloned version. Thanks!

**Comment by shamindras** [comment]
@mpadge - thanks for your prompt and helpful follow up. Also you correctly guessed - it is `maars` 🎉 !

I had not used [gert](https://docs.ropensci.org/gert/reference/git_fetch.html) before, so have now run this `reprex` per your request:

``` r
# Install packages - using pak
# install.packages("pak") # uncomment this if pak not installed
# pak::pkg_install("mpadge/allcontributors")

library(gert)
#> Linking to libgit2 v1.1.0, ssh support: YES
#> Global config: /Users/shamindras/.gitconfig
#> Default user: Shamindra Shrotriya <shamindra.shrotriya@gmail.com>
library(allcontributors)
git_dir <- file.path(tempdir(), 'maars')
git_clone('https://github.com/shamindras/maars.git', git_dir)
  
# Change into the repo directory
olddir <- getwd()
setwd(git_dir)
getwd()
#> [1] "/private/var/folders/b9/_ttxrgcn6t945cyff01hmfkr0000gn/T/RtmpNaqVRQ/maars"

# Show some stuff
git_log()
#> # A tibble: 20 x 6
#>    commit       author         time                files merge message          
#>  * <chr>        <chr>          <dttm>              <int> <lgl> <chr>            
#>  1 d27dcb59f20… Shamindra Shr… 2021-09-12 14:15:52    74 TRUE  "Merge pull requ…
#>  2 da635415717… Shamindra Shr… 2021-07-01 19:52:30   122 TRUE  "Merge pull requ…
#>  3 bddb14d0413… Shamindra Shr… 2021-05-02 11:30:16   104 TRUE  "Merge pull requ…
#>  4 23d7747a002… Shamindra Shr… 2021-03-31 23:38:59   143 TRUE  "Merge pull requ…
#>  5 652f1a8d57e… Shamindra Shr… 2021-03-19 07:38:04   139 TRUE  "Merge pull requ…
#>  6 0446e09561d… Shamindra Shr… 2021-03-10 16:02:27   137 TRUE  "Merge pull requ…
#>  7 5e738c45d32… Shamindra Shr… 2021-02-24 14:54:18    76 TRUE  "Merge pull requ…
#>  8 f25f5215bdd… Shamindra Shr… 2021-01-26 21:04:37    87 TRUE  "Merge pull requ…
#>  9 b37d88447ca… Shamindra Shr… 2021-01-26 19:25:58    46 TRUE  "Merge pull requ…
#> 10 62e07625194… Shamindra Shr… 2021-01-24 12:18:43    38 TRUE  "Merge pull requ…
#> 11 f1dc929a34e… Shamindra Shr… 2021-01-02 13:52:16    68 TRUE  "Merge pull requ…
#> 12 065459a705b… Shamindra Shr… 2021-01-01 15:55:23   102 TRUE  "Merge pull requ…
#> 13 03bb496f842… Shamindra Shr… 2020-11-30 13:00:27    69 TRUE  "Merge pull requ…
#> 14 97872eb91d3… Shamindra Shr… 2020-11-22 11:45:09    33 TRUE  "Merge pull requ…
#> 15 01d8b878fb9… ricfog <31448… 2020-11-15 16:28:22     1 TRUE  "Merge pull requ…
#> 16 cc84ebabcc2… Shamindra Shr… 2020-11-15 12:04:32    30 TRUE  "Merge pull requ…
#> 17 cf46addf724… Shamindra Shr… 2020-11-14 22:03:48    16 TRUE  "Merge pull requ…
#> 18 eadfdf0d737… Shamindra Shr… 2020-11-14 21:57:06     1 TRUE  "Merge pull requ…
#> 19 1df64c0f809… Shamindra Shr… 2020-11-14 21:46:50    15 TRUE  "Merge pull requ…
#> 20 60fa73e6319… Shamindra Shr… 2020-11-14 21:22:59     1 FALSE "Initial commit"
git_branch_list()
#> # A tibble: 4 x 6
#>   name     local ref          upstream      commit           updated            
#> * <chr>    <lgl> <chr>        <chr>         <chr>            <dttm>             
#> 1 main     TRUE  refs/heads/… refs/remotes… "d27dcb59f20b02… 2021-09-12 14:15:52
#> 2 origin/… FALSE refs/remote… <NA>          "a8a220a2b308a4… 2021-09-12 14:21:21
#> 3 origin/… FALSE refs/remote… <NA>          ""               1969-12-31 19:00:00
#> 4 origin/… FALSE refs/remote… <NA>          "d27dcb59f20b02… 2021-09-12 14:15:52
git_remote_list()
#> # A tibble: 1 x 2
#>   name   url                                    
#> * <chr>  <chr>                                  
#> 1 origin https://github.com/shamindras/maars.git

# Try adding all contributors to README.Rmd
allcontributors::add_contributors()
#> ٭  Extracting code contributors
#> Error: $ operator is invalid for atomic vectors

# Cleanup
setwd(olddir)
unlink(git_dir, recursive = TRUE)
```

<sup>Created on 2021-09-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Seems like this is the same issue I am getting. Please let me know if I've made a mistake in the `reprex` or if I could run more debugging on my end.

Many thanks.

<details>
    <summary><code>sessionInfo()</code></summary>
    R version 4.1.1 (2021-08-10)
    Platform: x86_64-apple-darwin17.0 (64-bit)
    Running under: macOS Big Sur 10.16

    Matrix products: default
    LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] allcontributors_0.0.2.009 gert_1.3.2               

    loaded via a namespace (and not attached):
    [1] highr_0.9         pillar_1.6.1      compiler_4.1.1    git2r_0.28.0      sys_3.4           tools_4.1.1      
    [7] digest_0.6.27     jsonlite_1.7.2    evaluate_0.14     lifecycle_1.0.0   tibble_3.1.2      pkgconfig_2.0.3  
    [13] rlang_0.4.11      reprex_2.0.1      cli_3.0.0         rstudioapi_0.13   curl_4.3.2        yaml_2.2.1       
    [19] xfun_0.24         withr_2.4.2       httr_1.4.2        styler_1.4.1      knitr_1.33        vctrs_0.3.8      
    [25] fs_1.5.0          askpass_1.1       rprojroot_2.0.2   glue_1.4.2        here_1.0.1        R6_2.5.0         
    [31] processx_3.5.2    fansi_0.5.0       rmarkdown_2.9     clipr_0.7.1       callr_3.7.0       purrr_0.3.4      
    [37] magrittr_2.0.1    backports_1.2.1   credentials_1.3.0 ps_1.6.0          ellipsis_0.3.2    htmltools_0.5.1.1
    [43] utf8_1.2.2        pak_0.1.2.9001    openssl_1.4.4     crayon_1.4.1
</details>

**Comment by mpadge** [comment]
Thanks @shamindras - i can reproduce that too. Shall fix asap

**Comment by mpadge** [comment]
It was because your git remote is set with a `.git` at the end, which is perfectly okay, and even good git practice, but something that I had not anticipated. Very easy to fix - thanks! I'll add you to the contribs list straight away :100:

**Comment by shamindras** [comment]
@mpadge - thanks again for your continued help.

I can confirm that the reprex above definitely runs correctly. However when I try locally, I get the following issue. I appreciate that this is not a full reprex, but not sure if I am doing something fundamentally wrong on my end locally:

``` r
here::here()
#> [1] "/private/var/folders/b9/_ttxrgcn6t945cyff01hmfkr0000gn/T/RtmpYRqjw8/reprex-e38d47b60d8b-neat-zebra"
library(allcontributors)
packageVersion("allcontributors")
#> [1] '0.0.2.13'
allcontributors::add_contributors()
#> Error in allcontributors::add_contributors(): The path [.] does not appear to be a git repository
```

<sup>Created on 2021-09-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Note, I also tried manually cloning `maars` to a new directory and running the above code (without `gert`) and got the same error. This was run on the latest `main` branch on `maars` at the time of cloning. This is a little confusing for me since I thought `gert` reprex would mirror the manual clone and run.

Please let me know if there are any issues with the repo or the way `allcontributors` is used here.

**Comment by mpadge** [comment]
That path is because `reprex` creates an entirely new temp directory to do its magic, so unless you explicitly tell it where you want to be, then `here:here()` won't give you the expected result, and `add_contributors()` won't work. That is perfectly normal, you just need to start with a `setwd()` line at the start of a `reprex`, or pass a path to the `add_contributors()` function.

**Comment by shamindras** [comment]
> That path is because `reprex` creates an entirely new temp directory to do its magic, so unless you explicitly tell it where you want to be, then `here:here()` won't give you the expected result, and `add_contributors()` won't work. That is perfectly normal, you just need to start with a `setwd()` line at the start of a `reprex`, or pass a path to the `add_contributors()` function.

Many thanks for explaining the `reprex` and `here::here()` relationship. Very helpful.

I guess locally the way I am running it currently is opening up `maars.Rproj` in a new RStudio session. Then once in my `maars.Rproj`, I simply call on `allcontributors::add_contributors()` from the R Console.

Is this the way I'm supposed to run it? This is what is effectively failing above, and how I understood the package was intended to be used. I want to ideally try and ensure that it works on my local workflow. This way I can train my team-members to use it, or create a short `Makefile` target, they will only run it this way (not using the `gert` type commands which are useful for debugging here).

**Comment by mpadge** [comment]
Yes, it definitely should just work in any repo. If you're still having issues, then please try to recreate again using a `reprex` like above, but ensuring an appropriate `setwd()` at the outset. (And by the way, `wd <- setwd(new)` will put the old directory in `wd` and change to the new one.)
