### ISSUE TITLE
Use gert?

### ISSUE THREAD

**Issue by maelle** [ropenscilabs/allcontributors#27]
Asking because I'm getting this error

```r
> allcontributors::add_contributors(repo = "igraph/rigraph")
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/maelle/R/x86_64-pc-linux-gnu-library/4.2/git2r/libs/git2r.so':
  libgit2.so.28: cannot open shared object file: No such file or directory
```

**Comment by mpadge** [comment]
There are still a few things that `git2r` does better. In this case, that is [the `in_repository()` function](https://docs.ropensci.org/git2r/reference/in_repository.html). `gert` generally chucks errors on a heap of useful things, including that. I suppose i could let `gert` do the depth trawling via `git_info()`, and just write a thin wrapper to catch the error, if that would help you?

**Comment by maelle** [comment]
I must say I wasn't able to install git2r properly and had to give up. I'll try again!

**Comment by mpadge** [comment]
I'll happily change it over then, and just write a simple `tryCatch()` wrapper to catch the `gert` errors. Watch this space ...

**Comment by mpadge** [comment]
Let me know how that goes ... :eyes:

**Comment by maelle** [comment]
Thank you!! I'm getting what's probably another error

```r
> allcontributors::add_contributors()
★  Extracting code contributorsError: $ operator is invalid for atomic vectors
Backtrace:
 1. allcontributors::add_contributors()
 2. allcontributors::get_contributors(...)
 3. allcontributors::get_gh_code_contributors(org, repo, alphabetical = alphabetical)
 4. base::vapply(x, function(i) i$login, character(1))
 5. allcontributors (local) FUN(X[[i]], ...)
 ```

the repo is my fork of https://github.com/igraph/rigraph/

**Comment by maelle** [comment]
`get_contributors(org="maelle", repo="rigraph")` works without any error. I got the other error for other repos as well. :thinking:

**Comment by mpadge** [comment]
But it breaks in the "Extracting code contributors" bit, right? That has to mean it breaks in the `get_contributors()` function. Can you maybe clone this repo, and try stepping through the code. Run the following lines first, then please step through `get_contributors()` in R/github.R:

``` r
# params:
repo = "."
ncols = 7
files = c ("README.Rmd", "README.md")
type = c ("code", "issues", "discussion")
exclude_label = "wontfix"
exclude_issues = NULL
exclude_not_planned = TRUE
num_sections = 3
section_names = c (
  "Code",
  "Issue Authors",
  "Issue Contributors"
)
format = "grid"
alphabetical = FALSE
open_issue = FALSE
force_update = FALSE

# from `add_contributors()`:
or <- allcontributors:::get_org_repo (repo)

# ctbs <- get_contributors (
#     or$org,
#     or$repo,
#     type = type,
#     exclude_label = exclude_label,
#     exclude_issues = exclude_issues,
#     exclude_not_planned = exclude_not_planned,
#     alphabetical = alphabetical,
#     quiet = FALSE
# )
org <- or$org
repo <- or$repo

# Then step through `get_contributors()` with the default param values from above ...
```
Thanks :exclamation: :+1: :smile:

**Comment by maelle** [comment]
is any specific scope necessary? I think that might be the problem.

**Comment by maelle** [comment]
ah no it's due to how the repo is guessed! the "git@github.com" hasn't been removed from the remote. I'll do a PR.
