### ISSUE TITLE
GitHub rate limit exceeded without warning/error

### ISSUE THREAD

**Issue by chartgerink** [ropenscilabs/allcontributors#36]
We've been having some issues with our use of `get_contributors()` over time, where we had to incorporate some delays to not surpass rate limits provisionally.

Would it be an option/idea to handle these rate limits a bit differently to let the person using the package know when this happens? For example, the function could throw an error in case the rate limit is exceeded. 

We got incomplete lists without the function failing, and it would've helped us if there was an error when the rate limit was exceeded. Now we thought it worked okay until manual inspection of the list. 

For reference: [The GitHub API](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) indicates the rate limit is exceeded if it happens, and [`gh::` has some functionality](https://gh.r-lib.org/reference/gh_rate_limit.html?q=rate#null) to check for this as well.

**Comment by mpadge** [comment]
That would indeed be a useful enhancement @chartgerink. Would you be willing and able to submit a pull request to update the code to include rate-limit checks and warnings?

**Comment by chartgerink** [comment]
Thanks @mpadge for the feedback! I can do that - I planned some time on the 27th to do it. 👍

**Comment by mpadge** [comment]
Awesome, that will be very much appreciated @chartgerink
