### ISSUE TITLE
429 errors with `add_contributors()`

### ISSUE THREAD

**Issue by sbfnk** [ropenscilabs/allcontributors#38]
We're running into 429 errors (too many requests) with `add_contributors()` and tracked this down to the `check_github_urls()` call. A simple remedy would be to expose the `check_urls` argument to `add_contributors()`. 

This issue is causing https://github.com/epiforecasts/EpiNow2/issues/664

**Comment by mpadge** [comment]
Just implemented a better work-around for a similar 429 error in https://github.com/ropensci-review-tools/dashboard/commit/c70e7af38c635232a415b4c7edce76d9e60ef912. I'll copy that code over here to fix. Thanks for the heads-up!

**Comment by mpadge** [comment]
@sbfnk The `check_urls` parameter has now been exposed in the main `add_contributors` function, as you suggested, plus additional error handling implemented for the checking calls themselves. Any errors should now just "fail gracefully", and the call should proceed regardless.

These changes should be on an updated CRAN version soon.
